set_device_name:
  name: Set device name
  description: Set a new name for the Ensto device
  fields:
    name:
      name: Name
      description: New name for the device
      required: true
      example: "Test Thermostat"
      selector:
        text:

set_device_time:
  name: Set device time
  description: Set Ensto device time to match Home Assistant time
  target:
    entity:
      integration: hass_ensto_ble
      domain: sensor
